
conn = new Mongo()
db = conn.getDB("music_db")

name = ["tokyo", "seoul", "numb", "somewhere", "whoami", "alltimelow", "alone", "ambient", "applause",
        "bean", "badbad", "beast", "lion", "roar", "tiger", "eyetoeye", "hello", "room", "hotel", "oneplus",
        "huawei", "warrior", "titanium", "lakers", "godcomplex", "help", "myname", "live", "humptydumpty",
        "all", "time", "low", "soar", "solar", "sore", "wounded", "hearts", "world", "earth", "heaven",
        "hell", "highway", "love", "life", "heartless", "india", "faith", "people"]

genre = ['rock', 'pop', 'edm', 'country']

var songArr = [{songID:1, songName: name[1], genre: genre[1], ownerID:1, songURL: '/uploads/' + name[1] + '.mp3', imgURL: '/uploads/' + name[1] + '.jpg'},
            {songID:2, songName: name[2], genre: genre[2], ownerID:3, songURL: '/uploads/' + name[2] + '.mp3', imgURL: '/uploads/' + name[2] + '.jpg'},
            {songID:3, songName: name[3], genre: genre[3], ownerID:2, songURL: '/uploads/' + name[3] + '.mp3', imgURL: '/uploads/' + name[3] + '.jpg'},
            {songID:4, songName: name[4], genre: genre[0], ownerID:3, songURL: '/uploads/' + name[4] + '.mp3', imgURL: '/uploads/' + name[4] + '.jpg'},
            {songID:5, songName: name[5], genre: genre[1], ownerID:2, songURL: '/uploads/' + name[5] + '.mp3', imgURL: '/uploads/' + name[5] + '.jpg'},
            {songID:6, songName: name[6], genre: genre[2], ownerID:3, songURL: '/uploads/' + name[6] + '.mp3', imgURL: '/uploads/' + name[6] + '.jpg'},
            {songID:7, songName: name[7], genre: genre[3], ownerID:2, songURL: '/uploads/' + name[7] + '.mp3', imgURL: '/uploads/' + name[7] + '.jpg'},
            {songID:8, songName: name[8], genre: genre[0], ownerID:1, songURL: '/uploads/' + name[8] + '.mp3', imgURL: '/uploads/' + name[8] + '.jpg'},
            {songID:9, songName: name[9], genre: genre[1], ownerID:1, songURL: '/uploads/' + name[9] + '.mp3', imgURL: '/uploads/' + name[9] + '.jpg'},
            {songID:10, songName: name[10], genre: genre[2], ownerID:3, songURL: '/uploads/' + name[10] + '.mp3', imgURL: '/uploads/' + name[10] + '.jpg'},
            {songID:11, songName: name[11], genre: genre[3], ownerID:4, songURL: '/uploads/' + name[11] + '.mp3', imgURL: '/uploads/' + name[11] + '.jpg'},
            {songID:12, songName: name[12], genre: genre[0], ownerID:1, songURL: '/uploads/' + name[12] + '.mp3', imgURL: '/uploads/' + name[12] + '.jpg'},
            {songID:13, songName: name[13], genre: genre[1], ownerID:4, songURL: '/uploads/' + name[13] + '.mp3', imgURL: '/uploads/' + name[13] + '.jpg'},
            {songID:14, songName: name[14], genre: genre[2], ownerID:4, songURL: '/uploads/' + name[14] + '.mp3', imgURL: '/uploads/' + name[14] + '.jpg'},
            {songID:15, songName: name[15], genre: genre[3], ownerID:4, songURL: '/uploads/' + name[15] + '.mp3', imgURL: '/uploads/' + name[15] + '.jpg'},
            {songID:16, songName: name[16], genre: genre[0], ownerID:4, songURL: '/uploads/' + name[16] + '.mp3', imgURL: '/uploads/' + name[16] + '.jpg'},
            {songID:17, songName: name[17], genre: genre[1], ownerID:4, songURL: '/uploads/' + name[17] + '.mp3', imgURL: '/uploads/' + name[17] + '.jpg'},
            {songID:18, songName: name[18], genre: genre[2], ownerID:2, songURL: '/uploads/' + name[18] + '.mp3', imgURL: '/uploads/' + name[18] + '.jpg'},
            {songID:19, songName: name[19], genre: genre[3], ownerID:1, songURL: '/uploads/' + name[19] + '.mp3', imgURL: '/uploads/' + name[19] + '.jpg'},
            {songID:20, songName: name[20], genre: genre[0], ownerID:2, songURL: '/uploads/' + name[20] + '.mp3', imgURL: '/uploads/' + name[20] + '.jpg'},
            {songID:21, songName: name[21], genre: genre[1], ownerID:3, songURL: '/uploads/' + name[21] + '.mp3', imgURL: '/uploads/' + name[21] + '.jpg'},
            {songID:22, songName: name[22], genre: genre[2], ownerID:2, songURL: '/uploads/' + name[22] + '.mp3', imgURL: '/uploads/' + name[22] + '.jpg'},
            {songID:23, songName: name[23], genre: genre[3], ownerID:2, songURL: '/uploads/' + name[23] + '.mp3', imgURL: '/uploads/' + name[23] + '.jpg'},
            {songID:24, songName: name[24], genre: genre[0], ownerID:1, songURL: '/uploads/' + name[24] + '.mp3', imgURL: '/uploads/' + name[24] + '.jpg'},
            {songID:25, songName: name[25], genre: genre[1], ownerID:3, songURL: '/uploads/' + name[25] + '.mp3', imgURL: '/uploads/' + name[25] + '.jpg'},
            {songID:26, songName: name[26], genre: genre[2], ownerID:3, songURL: '/uploads/' + name[26] + '.mp3', imgURL: '/uploads/' + name[26] + '.jpg'},
            {songID:27, songName: name[27], genre: genre[3], ownerID:4, songURL: '/uploads/' + name[27] + '.mp3', imgURL: '/uploads/' + name[27] + '.jpg'},
            {songID:28, songName: name[28], genre: genre[0], ownerID:4, songURL: '/uploads/' + name[28] + '.mp3', imgURL: '/uploads/' + name[28] + '.jpg'},
            {songID:29, songName: name[29], genre: genre[1], ownerID:2, songURL: '/uploads/' + name[29] + '.mp3', imgURL: '/uploads/' + name[29] + '.jpg'},
            {songID:30, songName: name[30], genre: genre[2], ownerID:2, songURL: '/uploads/' + name[30] + '.mp3', imgURL: '/uploads/' + name[30] + '.jpg'},
            {songID:31, songName: name[31], genre: genre[3], ownerID:2, songURL: '/uploads/' + name[31] + '.mp3', imgURL: '/uploads/' + name[31] + '.jpg'},
            {songID:32, songName: name[32], genre: genre[0], ownerID:4, songURL: '/uploads/' + name[32] + '.mp3', imgURL: '/uploads/' + name[32] + '.jpg'},
            {songID:33, songName: name[33], genre: genre[1], ownerID:1, songURL: '/uploads/' + name[33] + '.mp3', imgURL: '/uploads/' + name[33] + '.jpg'},
            {songID:34, songName: name[34], genre: genre[2], ownerID:2, songURL: '/uploads/' + name[34] + '.mp3', imgURL: '/uploads/' + name[34] + '.jpg'},
            {songID:35, songName: name[35], genre: genre[3], ownerID:4, songURL: '/uploads/' + name[35] + '.mp3', imgURL: '/uploads/' + name[35] + '.jpg'},
            {songID:36, songName: name[36], genre: genre[0], ownerID:1, songURL: '/uploads/' + name[36] + '.mp3', imgURL: '/uploads/' + name[36] + '.jpg'},
            {songID:37, songName: name[37], genre: genre[1], ownerID:1, songURL: '/uploads/' + name[37] + '.mp3', imgURL: '/uploads/' + name[37] + '.jpg'},
            {songID:38, songName: name[38], genre: genre[2], ownerID:4, songURL: '/uploads/' + name[38] + '.mp3', imgURL: '/uploads/' + name[38] + '.jpg'},
            {songID:39, songName: name[39], genre: genre[3], ownerID:4, songURL: '/uploads/' + name[39] + '.mp3', imgURL: '/uploads/' + name[39] + '.jpg'},
            {songID:40, songName: name[40], genre: genre[0], ownerID:1, songURL: '/uploads/' + name[40] + '.mp3', imgURL: '/uploads/' + name[40] + '.jpg'},
            {songID:41, songName: name[41], genre: genre[1], ownerID:1, songURL: '/uploads/' + name[41] + '.mp3', imgURL: '/uploads/' + name[41] + '.jpg'},
            {songID:42, songName: name[42], genre: genre[2], ownerID:3, songURL: '/uploads/' + name[42] + '.mp3', imgURL: '/uploads/' + name[42] + '.jpg'},
            {songID:43, songName: name[43], genre: genre[3], ownerID:4, songURL: '/uploads/' + name[43] + '.mp3', imgURL: '/uploads/' + name[43] + '.jpg'},
            {songID:44, songName: name[44], genre: genre[0], ownerID:4, songURL: '/uploads/' + name[44] + '.mp3', imgURL: '/uploads/' + name[44] + '.jpg'},
            {songID:45, songName: name[45], genre: genre[1], ownerID:3, songURL: '/uploads/' + name[45] + '.mp3', imgURL: '/uploads/' + name[45] + '.jpg'},
            {songID:46, songName: name[46], genre: genre[2], ownerID:4, songURL: '/uploads/' + name[46] + '.mp3', imgURL: '/uploads/' + name[46] + '.jpg'},
            {songID:47, songName: name[47], genre: genre[3], ownerID:4, songURL: '/uploads/' + name[47] + '.mp3', imgURL: '/uploads/' + name[47] + '.jpg'},
            {songID:48, songName: name[48], genre: genre[0], ownerID:3, songURL: '/uploads/' + name[48] + '.mp3', imgURL: '/uploads/' + name[48] + '.jpg'}];

//db.songs.insertMany(songArr)